spring:
  datasource:
      url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: password
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 9090
